spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flea_market?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 990611
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#文件上传路径
file-upload-path: D:\img

#邮箱配置
email-config:
  host: smtp.aliyun.com
  username: fleamarket@aliyun.com
  password: lyp82nlf

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
